import { Metadata } from "next";
import CategoryPageClient from "./CategoryPageClient";

export const metadata: Metadata = {
  title: "Giresun Rehber",
  description: "Generated by tolgabayrak",
};

export default async function CategoryPage({ params }: { params: { category: string } }) {
  return <CategoryPageClient category={params.category} />;
} 