import { Metadata } from "next";
import CategoryPageClient from "./CategoryPageClient";

export const metadata: Metadata = {
  title: "Giresun Rehber",
  description: "Generated by tolgabayrak",
};

interface CategoryPageProps {
  params: Promise<{ category: string }>;
}

export default async function CategoryPage({ params }: CategoryPageProps) {
  const resolvedParams = await params;
  const category = resolvedParams.category;
  
  return <CategoryPageClient category={category} />;
}
