import { Metadata } from "next";
import AboutPageClient from "./AboutPageClient";


export const metadata: Metadata = {
  title: "Giresun Rehber",
  description: "Generated by tolgabayrak",
};

export default function AboutPage() {
  return <AboutPageClient />;
} 